
obj-$(CONFIG_BLK_DEV_IDE_ICSIDE)	+= icside.o
obj-$(CONFIG_BLK_DEV_IDE_RAPIDE)	+= rapide.o
obj-$(CONFIG_BLK_DEV_IDE_BAST)		+= bast-ide.o
obj-$(CONFIG_BLK_DEV_IDE_EP93XX)        += ide-ep93xx.o
obj-$(CONFIG_BLK_DEV_IDE_DMA_EP93XX)    += ide-dma-ep93xx.o

EXTRA_CFLAGS	:= -Idrivers/ide
